Feat/adapt transformer based sentiments model to aam architecture using templates
Telefonica/aura-aam-t-sentiments pull request #1
Opened 2022-04-12 16:31 UTC by jesusdelpeso

This PR includes:

* Adapt the transformer-based baseline sentiment model to the repository structure defined in `aura-aam-template`, to integrate the model into the AAM architecture.
* Adapt the model training to follow the final AAM training flow.
* Create docker images for training and model serving.
* Include the model server.

Fixes [AURA-9831](https://jira.tid.es/browse/AURA-9831)

2022-04-21 11:43 UTC, CaroGG requested changes

2022-04-21 11:43 UTC, CaroGG commented on model_server/README.md
> +2. Make sure that the folder `./rest_server` is included in the `PYTHONPATH` virtual environment.
Update description: model server instead of rest_server

2022-04-21 11:43 UTC, CaroGG commented on src/aam_transformer_sentiment/constants.py
> +URL_SAS_TOKEN = 'URL_SAS_TOKEN'
Maybe we can remove this constant file as we are not using them anymore.

2022-04-21 11:59 UTC, jesusdelpeso commented on delivery/docker/Dockerfile.server
> +RUN pip3 install --trusted-host artifactory.hi.inet --extra-index-url http://artifactory.hi.inet/artifactory/api/pypi/pypi-aura-cognitive-cache/simple auracog-lib
Done

2022-04-21 12:02 UTC, jesusdelpeso commented on delivery/docker/Dockerfile.training
> +## 1.5 Install kubectl. Uncomment if you need to install kubectl, for example if you need to access a kubernetes cluster from this image.
This is just for local testing, before uploading the docker image to the registry. I would keep it here for the moment.

2022-04-21 12:09 UTC, jesusdelpeso commented on delivery/docker/Dockerfile.training
> +ENV MODEL_IMPLEMENTATION_VERSION=${MODEL_IMPLEMENTATION_VERSION}
This variable is passed as an argument to `docker build` in `build_training.sh` from the `VERSION.txt` file content. It is not needed to be declared in the variables file.

2022-04-21 12:11 UTC, jesusdelpeso commented on delivery/scripts/variables.sh.tpl
> +GITHUB_ACCESS_TOKEN=
Right. Fixed.

2022-04-21 12:13 UTC, jesusdelpeso commented on model_server/README.md
> +2. Make sure that the folder `./rest_server` is included in the `PYTHONPATH` virtual environment.
Right. Updated

2022-04-21 12:20 UTC, jesusdelpeso commented on src/aam_transformer_sentiment/constants.py
> +URL_SAS_TOKEN = 'URL_SAS_TOKEN'
Right. Not only this constant but the whole `constants.py` file can be removed.

2022-04-21 12:27 UTC, renerodriguezharo requested changes

2022-04-21 12:27 UTC, renerodriguezharo commented on scripts/train.py
> +from aura_aam_lib.common.aam import AamConfigException, AamSubmodel
AamConfigException is not used.

2022-04-21 12:27 UTC, renerodriguezharo commented on scripts/train.py
> +    model_id = model_name + "|" + model_version
Are we going to use the model_id variable?

2022-04-21 12:27 UTC, renerodriguezharo commented on scripts/train.py
> +def train_model(training_config: Dict, validation_config: Dict,
Is the logger needed here? Or is used in the main only?

2022-04-21 12:27 UTC, renerodriguezharo commented on scripts/train.py
> +#    print("Metrics validation result:{}".format(metrics_within_limits))
We can delete the validation here, since it is done in the main.

2022-04-21 12:27 UTC, renerodriguezharo commented on scripts/train.py
> +                       logger: logger_wrapper.LoggerWrapper, model_name: Text= None, model_version: Text= None,
Same as before. Is the logger needed here? Or is used in the main only?

2022-04-21 12:27 UTC, renerodriguezharo commented on scripts/train.py
> +                                    validation_config, logger)
We may need to validate before uploading to the MR so we can change the ready_to_deploy flag in case the validation is not okay.

2022-04-21 12:27 UTC, renerodriguezharo commented on scripts/train.py
> +                                    validation_config, logger)
Should we catch validation module exceptions here?

2022-04-21 12:32 UTC, jesusdelpeso commented on scripts/train.py
> +from aura_aam_lib.common.aam import AamConfigException, AamSubmodel
Removed

2022-04-21 12:33 UTC, jesusdelpeso commented on scripts/train.py
> +    model_id = model_name + "|" + model_version
It does not seem to be used. Removed.

2022-04-21 12:35 UTC, jesusdelpeso commented on scripts/train.py
> +def train_model(training_config: Dict, validation_config: Dict,
In the current training, it is not used. But the signature of the `train` method declares the `logger` argument to allow the developer to use the logger if needed.

2022-04-21 12:36 UTC, jesusdelpeso commented on scripts/train.py
> +#    print("Metrics validation result:{}".format(metrics_within_limits))
Right. Removed.

2022-04-21 12:49 UTC, jesusdelpeso commented on scripts/train.py
> +                       logger: logger_wrapper.LoggerWrapper, model_name: Text= None, model_version: Text= None,
It is not currently used, but it will be used in the future. I would refactor the `aura_aam_mr_client.mr.MR.check_model_version` method to return a boolean result and not to raise an exception. This is a better practice (leave raising exceptions for error reporting). The current implementation of this method makes it difficult to log the `check_model_exists` result. 
Since this is a minor feature, it is left for the future.

2022-04-21 13:02 UTC, jesusdelpeso commented on scripts/train.py
> +                                    validation_config, logger)
I prefer uploading the model to the MR as soon as the training is finished to ensure that the model is not lost due to some other posterior error. (The training may require many hours and resources!).
The `ready_to_deploy` flag can be updated later. 

Validation exceptions should be managed by the `ModelValidator` class.

2022-04-21 13:46 UTC, CaroGG commented on delivery/docker/Dockerfile.training
> +## 1.5 Install kubectl. Uncomment if you need to install kubectl, for example if you need to access a kubernetes cluster from this image.
I thought we had Dockerfile.training_kubectl and run_training_kubectl.sh for that, I mean that we had it already separated in a different dockerfile

2022-04-21 14:12 UTC, CaroGG requested changes

2022-04-21 14:12 UTC, CaroGG commented on delivery/scripts/run_server.sh
> +        -p ${SENTIMENTS_SERVER_PORT}:${SENTIMENTS_SERVER_PORT} $IMAGE_NAME:${VERSION}
What is the difference between SERVER_PORT and SENTIMENTS_SERVER_PORT?

2022-04-21 14:57 UTC, CaroGG requested changes

2022-04-21 14:57 UTC, CaroGG commented on delivery/scripts/build_server.sh
> +
Error when trying to create server image due to auracog_lib library

2022-04-21 15:51 UTC, jesusdelpeso commented on delivery/scripts/build_server.sh
> +
Fixed. It was needed to add ARG commands to the sever dockerfile and to pass the variables `ARTIFACTORY_REPO` and `ARTIFACTORY_HOST` as arguments to the `docker build` sentence.

2022-04-22 07:14 UTC, jesusdelpeso commented on delivery/docker/Dockerfile.training
> +## 1.5 Install kubectl. Uncomment if you need to install kubectl, for example if you need to access a kubernetes cluster from this image.
Right. The script adds some needed variables to run with kubernetes (set KUBECONFIG and mount the KUBECONFIG file), but the docker image still needs to install kubectl. This can only be done within the dockerfile.

2022-04-22 07:19 UTC, jesusdelpeso commented on delivery/scripts/run_server.sh
> +        -p ${SENTIMENTS_SERVER_PORT}:${SENTIMENTS_SERVER_PORT} $IMAGE_NAME:${VERSION}
`SENTIMENTS_SERVER_PORT` is wrong. It should be `SERVER_PORT` :-S
Fixed.

2022-04-22 07:22 UTC, CaroGG requested changes

2022-04-22 07:22 UTC, CaroGG commented on delivery/scripts/run_server.sh
> +source ./delivery/scripts/env_variables_server.sh
Should we remove this line?

2022-04-22 11:44 UTC, renerodriguezharo commented on delivery/docker/Dockerfile.server
> +ENV PYTHONPATH=./src:./rest_server
Should this be /model_server instead of /rest_server? Same in Dockerfile.server.tpl

2022-04-22 13:30 UTC, CaroGG submitted a review, later dismissed
LGTM

2022-04-25 07:37 UTC, jesusdelpeso commented on delivery/docker/Dockerfile.server
> +ENV PYTHONPATH=./src:./rest_server
Fixed

2022-04-25 07:57 UTC, jesusdelpeso commented on model_server/README.md
> +   - Set the environment variable URL_SAS_TOKEN="<URL_SAS_TOKEN>"
Right. Fixed

2022-04-25 07:59 UTC, renerodriguezharo approved these changes
LGTM

2022-04-25 09:45 UTC, CaroGG approved these changes
LGTM

2022-04-25 10:37 UTC, merged