Feat/modify_model_server_container_to_contain_default_model
Telefonica/aura-aam-t-sentiments pull request #4
Opened 2022-05-09 23:44 UTC by jesusdelpeso

This PR includes:

* Modify the model server Docker image to include a default model in the image local file system. This way the image can be run without an MR server. This change makes it possible to simplify the deployment of model server images.
* Add documentation on the creation and running of Docker images, both for training and for model serving.

Fixes [AURA-11838](https://jira.tid.es/browse/AURA-11838)

2022-05-11 14:51 UTC, CaroGG requested changes

2022-05-12 07:19 UTC, jesusdelpeso commented on delivery/scripts/download_default_model.sh
> +python3 delivery/scripts/download_model.py --config_file ${SERVER_CONFIG_FILE} --mr_host ${MR_HOST} --mr_port ${MR_PORT} \
Indeed, the SERVER_CONFIG_FILE variable definition seems to be missing :-S
I have added it (probably I have removed this line accidentally :-S)

2022-05-12 07:21 UTC, jesusdelpeso commented on delivery/scripts/run_server_variables.sh.tpl
> +#MODEL_SERVER_CONFIG=/home/jdpq/cto/aura-aam-t-sentiments/config/es/model_server_config.yaml
I have removed the value of the variable. I am afraid this was a remnant of some local tests I have done :-S

2022-05-13 07:43 UTC, CaroGG approved these changes
LGTM

2022-05-13 08:36 UTC, merged